version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - /var/www/relokia/php:/var/www/myapp
            - /var/www/relokia/docker/site.conf:/etc/nginx/conf.d/site.conf
        depends_on:
            - php
        restart: always
            
    php:
        image: php:7.4-fpm
        volumes:
            - /var/www/relokia/php:/var/www/myapp
            - /var/www/relokia/docker/php.ini:/usr/local/etc/php/php.ini